### ISSUE TITLE
Ablog install on Windows

### ISSUE THREAD

**Issue by gigster99** [abakan/ablog#37]
Am trying to install Ablog under WIndows, but get the following error message.
```
#   ablog (unknown version) from C:\bin\python\lib\site-packages\ablog\__init__.py
#   alabaster (0.7.3) from C:\bin\python\lib\site-packages\alabaster\__init__.py
Traceback (most recent call last):
  File "C:\bin\python\lib\site-packages\sphinx\cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "C:\bin\python\lib\site-packages\sphinx\application.py", line 264, in build
    self.builder.build_update()
  File "C:\bin\python\lib\site-packages\sphinx\builders\__init__.py", line 245, in build_update
    'out of date' % len(to_build))
  File "C:\bin\python\lib\site-packages\sphinx\builders\__init__.py", line 319, in build
    self.finish()
  File "C:\bin\python\lib\site-packages\sphinx\builders\html.py", line 456, in finish
    self.finish_tasks.add_task(self.gen_additional_pages)
  File "C:\bin\python\lib\site-packages\sphinx\util\parallel.py", line 39, in add_task
    res = task_func()
  File "C:\bin\python\lib\site-packages\sphinx\builders\html.py", line 482, in gen_additional_pages
    self.handle_page(pagename, context, template)
  File "C:\bin\python\lib\site-packages\sphinx\builders\html.py", line 786, in handle_page
    output = self.templates.render(templatename, ctx)
  File "C:\bin\python\lib\site-packages\sphinx\jinja2glue.py", line 138, in render
    return self.environment.get_template(template).render(context)
  File "C:\bin\python\lib\site-packages\jinja2-2.7.3-py3.4.egg\jinja2\environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\bin\python\lib\site-packages\jinja2-2.7.3-py3.4.egg\jinja2\environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\bin\python\lib\site-packages\jinja2-2.7.3-py3.4.egg\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\bin\python\lib\site-packages\sphinx\jinja2glue.py", line 159, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: catalog.html
```
My template path looks like this:

templates_path = [
                  '_templates',
                  'templates_path.append(ablog.get_html_templates_path())'
                  ]

What should I do to correctly install ablog?
Thanks for your assistance.
/gg

**Comment by abakan** [comment]
Your templates pat variable should look like:
```
templates_path = [
'_templates',
templates_path.append(ablog.get_html_templates_path())
]
```
That's, remove ' from around secons item. Let me know if you still have problems.

**Comment by gigster99** [comment]
This addition works for me now:

 

templates_path = [

                  '_templates',

                  ablog.get_html_templates_path()

                 ]

 

I found it in your config.py (which is where I should have looked to begin with!).

 

This one does not work when combined with template_path = []

       templates_path.append(ablog.get_html_templates_path())

 

Thank you for your help.

We plan to integrate ablog with an existing project:

       http://nutrients.readthedocs.org/en/latest/index.html

We plan to use this theme:

       http://casperjs.readthedocs.org/en/latest/

So will have some work to do to modify ablog CSS.

Hope I can ask more questions if we encounter issues or need advice.

BR,

/gig
