### ISSUE TITLE
linux install error

### ISSUE THREAD

**Issue by gigster99** [abakan/ablog#38]
When installing ablog on a test linux server, one of my team mates is getting this error message.

Exception occurred:
  File "/home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/ablog/blog.py", line 228, in recent
    num += 1
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'

"nutriben" is the physical name of the site.
The test linx server is:
*   Ubuntu 14.04 with LAMP server.
*   Python 3.3 under virtualenvironment.

Are we doing something wrong, or is there a work around for this?

/gg

**Comment by abakan** [comment]
You should include full traceback if possible, so that i can tell what caused the exception.

**Comment by gigster99** [comment]
here is the full traceck ...
```
# Sphinx version: 1.3.1
# Python version: 3.3.6 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Last messages:
#   writing output... [ 93%] 13_dir/$_13-bibliography-3-book-food-ref
#   writing output... [ 94%] 13_dir/$_13-bibliography-4-article-food-ref
#   writing output... [ 95%] 13_dir/$_13-bibliography-5-misc-ontology
#   writing output... [ 95%] 13_dir/$_13-bibliography-6-misc-data
#   writing output... [ 96%] 13_dir/$_13-bibliography-7-misc-web
#   writing output... [ 97%] 13_dir/$_13-bibliography-8-article-technology
#   writing output... [ 97%] 15_dir/$_15-ontomatica
#   writing output... [ 98%] 15_dir/$_15-ontomatica-exec-summary
#   writing output... [ 99%] 15_dir/$_15-ontomatica-expertise
#   writing output... [100%] index
# Loaded extensions:
#   sphinx.ext.viewcode (1.3.1) from /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinx/ext/viewcode.py
#   ablog (unknown version) from /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/ablog/__init__.py
#   sphinxcontrib.images (unknown version) from /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinxcontrib/images.py
#   sphinxcontrib.exceltable (unknown version) from /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinxcontrib/exceltable.py
#   sphinx.ext.doctest (1.3.1) from /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.ifconfig (1.3.1) from /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinx/ext/ifconfig.py
#   sphinxcontrib.httpdomain (unknown version) from /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinxcontrib/httpdomain.py
#   alabaster (0.7.3) from /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/alabaster/__init__.py
#   sphinx.ext.mathjax (1.3.1) from /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.bibtex (unknown version) from /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinxcontrib/bibtex/__init__.py
#   sphinx.ext.intersphinx (1.3.1) from /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.autodoc (1.3.1) from /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinx/ext/autodoc.py
#   sphinxcontrib.jsdemo (unknown version) from /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinxcontrib_jsdemo-0.1.4-py3.3.egg/sphinxcontrib/jsdemo.py
#   sphinxcontrib.napoleon (unknown version) from /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinxcontrib/napoleon/__init__.py
#   sphinx.ext.coverage (1.3.1) from /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinx/ext/coverage.py
Traceback (most recent call last):
  File "/home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinx/cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "/home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinx/application.py", line 264, in build
    self.builder.build_update()
  File "/home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinx/builders/__init__.py", line 245, in build_update
    'out of date' % len(to_build))
  File "/home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinx/builders/__init__.py", line 316, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinx/builders/__init__.py", line 354, in write
    self._write_serial(sorted(docnames), warnings)
  File "/home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinx/builders/__init__.py", line 360, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinx/environment.py", line 1291, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "/home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinx/environment.py", line 1570, in resolve_references
    builder.app.emit('doctree-resolved', doctree, fromdocname)
  File "/home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/sphinx/application.py", line 497, in emit
    results.append(callback(self, *args))
  File "/home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/ablog/post.py", line 369, in process_postlist
    **node.attributes))
  File "/home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages/ablog/blog.py", line 228, in recent
    num += 1
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'
```
here is the output from pip install -U ablog

```
:~/virtualenvs/sphinx/doc_ablog_github/docs$ pip install -U ablog

Requirement already up-to-date: ablog in /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages
Requirement already up-to-date: Werkzeug in /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages (from ablog)
Requirement already up-to-date: Sphinx in /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages (from ablog)
Requirement already up-to-date: alabaster in /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages (from ablog)
Requirement already up-to-date: invoke in /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages (from ablog)
Requirement already up-to-date: sphinx-rtd-theme<0.2,>=0.1 in /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages (from Sphinx->ablog)
Requirement already up-to-date: snowballstemmer>=1.1 in /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages (from Sphinx->ablog)
Requirement already up-to-date: Pygments>=2.0 in /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages (from Sphinx->ablog)
Requirement already up-to-date: docutils>=0.11 in /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages (from Sphinx->ablog)
Requirement already up-to-date: six>=1.4 in /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages (from Sphinx->ablog)
Requirement already up-to-date: Jinja2>=2.3 in /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages (from Sphinx->ablog)
Requirement already up-to-date: babel>=1.3 in /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages (from Sphinx->ablog)
Requirement already up-to-date: markupsafe in /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages (from Jinja2>=2.3->Sphinx->ablog)
Requirement already up-to-date: pytz>=0a in /home/nutriben/virtualenvs/sphinx/lib/python3.3/site-packages (from babel>=1.3->Sphinx->ablog)
```

**Comment by abakan** [comment]
Thanks for the details. Could you try with v0.6.5, and let me know if this persists?

**Comment by abakan** [comment]
I suppose this is not anymore an issue with the latest release.
