### ISSUE TITLE
Ablog and ReadTheDoc server

### ISSUE THREAD

**Issue by gigster99** [abakan/ablog#39]
Ablog works correctly when compiled under `Windows` using the `ReadTheDoc theme`.

However, when compiling the same `RST` files with Ablog on `ReadTheDoc server`, we get this error message:
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-1/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-1/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 212, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-1/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 214, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-1/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 256, in build
    self.env.topickle(path.join(self.doctreedir, ENV_PICKLE_FILENAME))
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-1/envs/latest/local/lib/python2.7/site-packages/sphinx/environment.py", line 146, in topickle
    pickle.dump(self, picklefile, pickle.HIGHEST_PROTOCOL)
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-1/envs/latest/local/lib/python2.7/site-packages/sphinx/environment.py", line 146, in topickle
    pickle.dump(self, picklefile, pickle.HIGHEST_PROTOCOL)
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

The full traceback has been saved in /tmp/sphinx-err-VjNexP.log
```

We are using a `requirements.txt` file that includes `ablog` and `alabaster` and `werkzeug`.

What are we doing wrong?

**Comment by abakan** [comment]
Can you try adding the following two lines to your `conf.py` file:

```python
if os.environ.get('READTHEDOCS', None) == 'True':
    skip_pickling = True
```

That's what I have to make ABlog documentation build on ReadTheDocs.

**Comment by gigster99** [comment]
TY - works perfectly.
