### ISSUE TITLE
Uncaught exception in `ablog -deploy`

### ISSUE THREAD

**Issue by isedwards** [abakan/ablog#53]
If `github_pages` is not set in `conf.py` an AttributeError is raised:

    $ ablog deploy
    Traceback (most recent call last):
      File "/usr/local/bin/ablog", line 9, in <module>
        load_entry_point('ablog==0.8.0', 'console_scripts', 'ablog')()
      File "/usr/local/lib/python2.7/dist-packages/ablog/commands.py", line 401, in ablog_main
        namespace.func(**namespace.__dict__)
      File "/usr/local/lib/python2.7/dist-packages/ablog/commands.py", line 318, in ablog_deploy
        github_pages = (github_pages or getattr(conf, 'github_pages') or None)
    AttributeError: 'module' object has no attribute 'github_pages'

**Comment by abakan** [comment]
Thanks for reporting.
