### ISSUE TITLE
failed to pip install ablog

### ISSUE THREAD

**Issue by Mizuchi** [abakan/ablog#59]
I got such error when I was trying to install ablog

	% pip install ablog
	Downloading/unpacking ablog
	  Running setup.py egg_info for package ablog
	    Traceback (most recent call last):
	      File "<string>", line 14, in <module>
	      File "/tmp/build/ablog/setup.py", line 62, in <module>
		'ablog{} = ablog.commands:ablog_main'.format(sys.version_info[0]),
	    ValueError: zero length field name in format
	    Complete output from command python setup.py egg_info:
	    Traceback (most recent call last):

	  File "<string>", line 14, in <module>

	  File "/tmp/build/ablog/setup.py", line 62, in <module>

	    'ablog{} = ablog.commands:ablog_main'.format(sys.version_info[0]),

	ValueError: zero length field name in format

	----------------------------------------
	Command python setup.py egg_info failed with error code 1
	Storing complete log in /home/ytj/.pip/pip.log

I guess this is because ablog doesn't support python2.6 (all dependencies and they support python 2.6+ and 3.3+, so I think this is ablog's issue). It would be better if we could specific the supported python version in README.

**Comment by Mizuchi** [comment]
full trace:

	------------------------------------------------------------
	/usr/bin/pip-python run on Tue Jan  5 13:50:31 2016
	Downloading/unpacking ablog
	  Running setup.py egg_info for package ablog
	    Traceback (most recent call last):
	      File "<string>", line 14, in <module>
	      File "/tmp/build/ablog/setup.py", line 62, in <module>
		'ablog{} = ablog.commands:ablog_main'.format(sys.version_info[0]),
	    ValueError: zero length field name in format
	    Complete output from command python setup.py egg_info:
	    Traceback (most recent call last):

	  File "<string>", line 14, in <module>

	  File "/tmp/build/ablog/setup.py", line 62, in <module>

	    'ablog{} = ablog.commands:ablog_main'.format(sys.version_info[0]),

	ValueError: zero length field name in format

	----------------------------------------
	Command python setup.py egg_info failed with error code 1
	Exception information:
	Traceback (most recent call last):
	  File "/usr/lib/python2.6/site-packages/pip/basecommand.py", line 124, in main
	    self.run(options, args)
	  File "/usr/lib/python2.6/site-packages/pip/commands/install.py", line 178, in run
	    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
	  File "/usr/lib/python2.6/site-packages/pip/req.py", line 927, in prepare_files
	    req_to_install.run_egg_info()
	  File "/usr/lib/python2.6/site-packages/pip/req.py", line 219, in run_egg_info
	    command_desc='python setup.py egg_info')
	  File "/usr/lib/python2.6/site-packages/pip/__init__.py", line 239, in call_subprocess
	    % (command_desc, proc.returncode))
	InstallationError: Command python setup.py egg_info failed with error code 1

**Comment by abakan** [comment]
I made some fixes to support Python 2.6: https://travis-ci.org/abakan/ablog/builds/100459363

Can you try `https://github.com/abakan/ablog/archive/devel.zip`?
