### ISSUE TITLE
ablog serve - Address already in use

### ISSUE THREAD

**Issue by rgrinberg** [abakan/ablog#69]
Try running `$ ablog serve` followed by `C-c` and `$ ablog serve` again. You will usually get:

```
Traceback (most recent call last):
  File "/usr/bin/ablog", line 9, in <module>
    load_entry_point('ablog==0.8.3', 'console_scripts', 'ablog')()
  File "/usr/lib/python3.5/site-packages/ablog-0.8.3-py3.5.egg/ablog/commands.py", line 408, in ablog_main
    namespace.func(**namespace.__dict__)
  File "/usr/lib/python3.5/site-packages/ablog-0.8.3-py3.5.egg/ablog/commands.py", line 203, in ablog_serve
    httpd = socketserver.TCPServer(("", port), Handler)
  File "/usr/lib/python3.5/socketserver.py", line 443, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/socketserver.py", line 457, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

Quite annoying for development...

**Comment by rgrinberg** [comment]
Sweet. Can we get a release in pip?

**Comment by abakan-zz** [comment]
New version release, but without a release note :(
