### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'env'

### ISSUE THREAD

**Issue by lsaffre** [abakan/ablog#88]
Here is a problem when I try to build my doctree with Sphinx 1.6.2. (current workaround is to run pip install "Sphinx==1.5.6")

```
# Sphinx version: 1.6.2
# Python version: 2.7.12 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:
#   writing output... [ 99%] reden/wissen
#   writing output... [ 99%] reden/wohin
#   writing output... [100%] tags/index
#   
#   generating indices...
#   
#   pickling environment...
#   done
#   checking consistency...
#   done
# Loaded extensions:
#   ablog (0.8.4) from /media/dell1tb/work/ablog/ablog/__init__.pyc
#   sphinx.ext.inheritance_diagram (1.6.2) from /media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/ext/inheritance_diagram.pyc
#   atelier.sphinxconf.base (unknown version) from /media/dell1tb/work/atelier/atelier/sphinxconf/base.pyc
#   atelier.sphinxconf.insert_input (unknown version) from /media/dell1tb/work/atelier/atelier/sphinxconf/insert_input.pyc
#   sphinxcontrib.youtube (unknown version) from /media/dell1tb/repositories/sphinxcontrib.youtube/sphinxcontrib/youtube/__init__.pyc
#   atelier.sphinxconf.refstothis (unknown version) from /media/dell1tb/work/atelier/atelier/sphinxconf/refstothis.pyc
#   sphinx.ext.todo (1.6.2) from /media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/ext/todo.pyc
#   sphinx.ext.autodoc (1.6.2) from /media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.intersphinx (1.6.2) from /media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/ext/intersphinx.pyc
#   atelier.sphinxconf.dirtables (unknown version) from /media/dell1tb/work/atelier/atelier/sphinxconf/dirtables.pyc
#   sphinx.ext.graphviz (1.6.2) from /media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/ext/graphviz.pyc
#   alabaster (0.7.10) from /media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/alabaster/__init__.pyc
#   atelier.sphinxconf.blog (unknown version) from /media/dell1tb/work/atelier/atelier/sphinxconf/blog.pyc
#   atelier.sphinxconf.sigal_image (unknown version) from /media/dell1tb/work/atelier/atelier/sphinxconf/sigal_image.pyc
#   sphinx.ext.extlinks (1.6.2) from /media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/ext/extlinks.pyc
#   sphinxfeed (unknown version) from /media/dell1tb/work/sphinxfeed/sphinxfeed.pyc
#   sphinx.ext.autosummary (1.6.2) from /media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/ext/autosummary/__init__.pyc
Traceback (most recent call last):
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 328, in build_update
    'out of date' % len(to_build))
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 397, in build
    self.finish()
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 574, in finish
    self.finish_tasks.add_task(self.gen_additional_pages)
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/util/parallel.py", line 49, in add_task
    res = task_func()
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 602, in gen_additional_pages
    self.handle_page(pagename, context, template)
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 945, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/jinja2glue.py", line 176, in render
    return self.environment.get_template(template).render(context)
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/media/dell1tb/work/ablog/ablog/templates/collection.html", line 1, in top-level template code
    {%- extends "page.html" %}
  File "/media/dell1tb/work/ablog/ablog/templates/page.html", line 2, in top-level template code
    {% set fa = ablog.fontawesome %}
  File "/media/dell1tb/luc/mypy/lino_local/lucde/docs/.templates/layout.html", line 2, in top-level template code
    {% set css_files = css_files + ["_static/myalabaster.css", "_static/tzverses.css"] %}
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/alabaster/layout.html", line 1, in top-level template code
    {%- extends "basic/layout.html" %}
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/themes/basic/../basic/layout.html", line 171, in top-level template code
    {%- block content %}
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/alabaster/layout.html", line 40, in block "content"
    {{ super() }}
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/jinja2/sandbox.py", line 427, in call
    return __context.call(__obj, *args, **kwargs)
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/themes/basic/../basic/layout.html", line 175, in block "content"
    {%- block document %}
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/alabaster/layout.html", line 30, in block "document"
    {% block body %} {% endblock %}
  File "/media/dell1tb/work/ablog/ablog/templates/collection.html", line 47, in block "body"
    {{ post.to_html(collection.docname) }}
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/jinja2/sandbox.py", line 427, in call
    return __context.call(__obj, *args, **kwargs)
  File "/media/dell1tb/work/ablog/ablog/blog.py", line 397, in to_html
    app.env.resolve_references(doctree, pagename, app.builder)
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 943, in resolve_references
    self.apply_post_transforms(doctree, fromdocname)
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 955, in apply_post_transforms
    transformer.apply_transforms()
  File "/media/dell1tb/virtualenvs/py27/local/lib/python2.7/site-packages/sphinx/transforms/__init__.py", line 90, in apply_transforms
    self.document.settings.env = self.env
AttributeError: 'dict' object has no attribute 'env'

```
Let me know if you need more information.

**Comment by AlbertMietus** [comment]
I remember this one ...

I made a fix in my clone. Maybe that helps fixing this one

As I away and offline, I can't check myself

--albert
An iPhone is great, but for typing mail

**Comment by lsaffre** [comment]
Thanks Albert, but I could not find your fix and now I found a cruel workaround : I disabled the ablog extension after realizing that I actually don't really need it.

**Comment by DuyguKeskek** [comment]
@lsaffre  @AlbertMietus  I disabled the ablog extension also but it didn't work. I have to fix this error to run Ablog, how did you achieve that ?
