### ISSUE TITLE
Blocker: "ImportError: cannot import name make_admonition"

### ISSUE THREAD

**Issue by getreu** [abakan/ablog#95]
My fresh install. See version numbers.

```
pip install ablog -U
Collecting ablog
  Downloading ablog-0.8.4.tar.gz
Collecting Sphinx (from ablog)
  Downloading Sphinx-1.6.5-py2.py3-none-any.whl (1.9MB)
    100% |████████████████████████████████| 1.9MB 453kB/s 
Collecting Werkzeug (from ablog)
  Downloading Werkzeug-0.12.2-py2.py3-none-any.whl (312kB)
    100% |████████████████████████████████| 317kB 952kB/s 
Collecting alabaster (from ablog)
  Downloading alabaster-0.7.10-py2.py3-none-any.whl
Collecting invoke (from ablog)
  Downloading invoke-0.21.0-py2-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 1.1MB/s 
Collecting python-dateutil (from ablog)
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 976kB/s 
Collecting sphinxcontrib-websupport (from Sphinx->ablog)
  Downloading sphinxcontrib_websupport-1.0.1-py2.py3-none-any.whl
Collecting six>=1.5 (from Sphinx->ablog)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting requests>=2.0.0 (from Sphinx->ablog)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 1.3MB/s 
Collecting docutils>=0.11 (from Sphinx->ablog)
  Downloading docutils-0.14-py2-none-any.whl (543kB)
    100% |████████████████████████████████| 552kB 906kB/s 
Collecting typing; python_version < "3.5" (from Sphinx->ablog)
  Downloading typing-3.6.2-py2-none-any.whl
Collecting Pygments>=2.0 (from Sphinx->ablog)
  Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB)
    100% |████████████████████████████████| 849kB 730kB/s 
Collecting setuptools (from Sphinx->ablog)
  Downloading setuptools-36.6.0-py2.py3-none-any.whl (481kB)
    100% |████████████████████████████████| 481kB 943kB/s 
Collecting imagesize (from Sphinx->ablog)
  Downloading imagesize-0.7.1-py2.py3-none-any.whl
Collecting babel!=2.0,>=1.3 (from Sphinx->ablog)
  Downloading Babel-2.5.1-py2.py3-none-any.whl (6.8MB)
    100% |████████████████████████████████| 6.8MB 182kB/s 
Collecting snowballstemmer>=1.1 (from Sphinx->ablog)
  Downloading snowballstemmer-1.2.1-py2.py3-none-any.whl (64kB)
    100% |████████████████████████████████| 71kB 1.4MB/s 
Collecting Jinja2>=2.3 (from Sphinx->ablog)
  Downloading Jinja2-2.9.6-py2.py3-none-any.whl (340kB)
    100% |████████████████████████████████| 348kB 1.2MB/s 
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.0.0->Sphinx->ablog)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 1.0MB/s 
Collecting idna<2.7,>=2.5 (from requests>=2.0.0->Sphinx->ablog)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 1.8MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.0.0->Sphinx->ablog)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 1.2MB/s 
Collecting certifi>=2017.4.17 (from requests>=2.0.0->Sphinx->ablog)
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
    100% |████████████████████████████████| 358kB 959kB/s 
Collecting pytz>=0a (from babel!=2.0,>=1.3->Sphinx->ablog)
  Downloading pytz-2017.3-py2.py3-none-any.whl (511kB)
    100% |████████████████████████████████| 512kB 908kB/s 
Collecting MarkupSafe>=0.23 (from Jinja2>=2.3->Sphinx->ablog)
  Downloading MarkupSafe-1.0.tar.gz
Building wheels for collected packages: ablog, MarkupSafe
  Running setup.py bdist_wheel for ablog ... done
  Stored in directory: /root/.cache/pip/wheels/d4/fe/45/3ff67a23d38097781dd6c09fe9af42d7368d57882871580272
  Running setup.py bdist_wheel for MarkupSafe ... done
  Stored in directory: /root/.cache/pip/wheels/88/a7/30/e39a54a87bcbe25308fa3ca64e8ddc75d9b3e5afa21ee32d57
Successfully built ablog MarkupSafe
Installing collected packages: sphinxcontrib-websupport, six, urllib3, idna, chardet, certifi, requests, docutils, typing, Pygments, setuptools, imagesize, pytz, babel, snowballstemmer, MarkupSafe, Jinja2, alabaster, Sphinx, Werkzeug, invoke, python-dateutil, ablog
  Found existing installation: six 1.10.0
    Not uninstalling six at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: urllib3 1.19.1
    Not uninstalling urllib3 at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: idna 2.2
    Not uninstalling idna at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: chardet 2.3.0
    Not uninstalling chardet at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: requests 2.12.4
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: setuptools 33.1.1
    Not uninstalling setuptools at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: MarkupSafe 0.23
    Not uninstalling markupsafe at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: Jinja2 2.8
    Not uninstalling jinja2 at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: python-dateutil 2.5.3
    Not uninstalling python-dateutil at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed Jinja2-2.9.6 MarkupSafe-1.0 Pygments-2.2.0 Sphinx-1.6.5 Werkzeug-0.12.2 ablog-0.8.4 alabaster-0.7.10 babel-2.5.1 certifi-2017.7.27.1 chardet-3.0.4 docutils-0.14 idna-2.6 imagesize-0.7.1 invoke-0.21.0 python-dateutil-2.6.1 pytz-2017.3 requests-2.18.4 setuptools-36.6.0 six-1.11.0 snowballstemmer-1.2.1 sphinxcontrib-websupport-1.0.1 typing-3.6.2 urllib3-1.22
root@k1:~# 
```

I get this error when I try to build my blog.

```
user@k1:.../blog$ ablog build
/usr/local/lib/python2.7/dist-packages/sphinx/util/compat.py:40: RemovedInSphinx17Warning: sphinx.util.compat.Directive is deprecated and will be removed in Sphinx 1.7, please use docutils' instead.
  RemovedInSphinx17Warning)
Traceback (most recent call last):
  File "/usr/local/bin/ablog", line 7, in <module>
    from ablog.commands import ablog_main
  File "/usr/local/lib/python2.7/dist-packages/ablog/__init__.py", line 6, in <module>
    from .post import (PostDirective, PostListDirective, UpdateDirective,
  File "/usr/local/lib/python2.7/dist-packages/ablog/post.py", line 16, in <module>
    from sphinx.util.compat import Directive, make_admonition
ImportError: cannot import name make_admonition
```

**Comment by getreu** [comment]
I just saw, this is a duplicate of issue #92 . I close this.
